In [8]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus/#countries', 'html.parser')
soup =requests.get(url)
soup =BeautifulSoup(soup.text, "lxml")
soup

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID - Coronavirus Statistics - Worldometer</title>
<meta content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates." name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: May 05, 2023, 07:06 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">687,576,650        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,869,692</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>660,014,861</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">20,692,097</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">20,652,902</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">39,195</span> (<strong>0.2</strong>%)
                                    <div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>
<a class="flip_cases_front" href="javascript: void(0);" style="clear: both;display: block;padding-top:20px;width:100%;">Show Graph</a>
</div>
<div class="panel_back" style="width:100%;height:100%;">
<div id="total-currently-infected-linear"></div>

In [9]:
table_code = soup.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>126,309,685</td>
<td></td>
<td>1,630,352</td>
<td></td>
<td>122,090,281</td>
<td>+1,003</td>
<td>2,589,052</td>
<td>6,413</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>216,724,187</td>
<td>+18,459</td>
<td>1,544,873</td>
<td>+6</td>
<td>200,607,206</td>
<td>+4,932</td>
<td>14,572,108</td>
<td>15,649</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>248,938,503</td>
<td></td>
<td>2,053,808</td>
<td></td>
<td>244,762,390</td>
<td>+2,996</td>
<td>2,122,305</td>
<td>6,362</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,600,642</td>
<td></td>
<td>1,354,635</td>
<td></td>
<td>66,449,498</td>
<td></td>
<td>796,509</td>
<td>10,134</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,182,986</td>
<td></td>
<td>27,278</td>
<td></td>
<td>14,020,441</td>
<td></td>
<td>135,267</td>
<td>89</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,819,926</td>
<td></td>
<td>258,731</td>
<td></td>
<td>12,084,339</td>
<td></td>
<td>476,856</td>
<td>548</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>687,576,650</td>
<td>+18,459</td>
<td>6,869,692</td>
<td>+6</td>
<td>660,014,861</td>
<td>+8,903</td>
<td>20,692,097</td>
<td>39,195</td>
<td>88,210</td>
<td>881.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">106,762,797</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,162,403                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">104,699,401</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">900,993</td>
<td style="font-weight: bold; text-align:right">1,247</td>
<td style="font-weight: bold; text-align:right">318,880</td>
<td style="font-weight: bold; text-align:right">3,472</td>
<td style="font-weight: bold; text-align:right">1,178,666,374</td>
<td style="font-weight: bold; text-align:right">3,520,453</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>288</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,691</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,960,678</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">531,606                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,392,828</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">36,244</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,963</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">927,239,236</td>
<td style="font-weight: bold; text-align:right">659,191</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,646</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">26</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,007,281</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">166,645                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,720,963</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">119,673</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">610,011</td>
<td style="font-weight: bold; text-align:right">2,541</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>394</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,825</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,409,620</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">173,307                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,204,800</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">31,513</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">457,892</td>
<td style="font-weight: bold; text-align:right">2,066</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>484</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">376</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,487,971</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">701,833                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">536,977</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">174,076</td>
<td style="font-weight: bold; text-align:right">3,259</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>307</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,493</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,766,957</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,614                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">71</td>
<td style="font-weight: bold; text-align:right">268,878</td>
<td style="font-weight: bold; text-align:right">594</td>
<td style="font-weight: bold; text-align:right">100,342,320</td>
<td style="font-weight: bold; text-align:right">799,000</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,683</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,291</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">31,251,203</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,459</td>
<td style="font-weight: bold; text-align:right;">34,518                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+6</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,959,576</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,939</td>
<td style="text-align:right;font-weight:bold;">257,109</td>
<td style="font-weight: bold; text-align:right">141</td>
<td style="font-weight: bold; text-align:right">608,830</td>
<td style="font-weight: bold; text-align:right">672</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,487</td><td>3</td>
<td style="font-weight: bold; text-align:right">360</td>
<td style="font-weight: bold; text-align:right">0.1</td>
<td style="font-weight: bold; text-align:right">5,009</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,788,387</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">189,738                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,468,617</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">130,032</td>
<td style="font-weight: bold; text-align:right">100</td>
<td style="font-weight: bold; text-align:right">427,932</td>
<td style="font-weight: bold; text-align:right">3,149</td>
<td style="font-weight: bold; text-align:right">271,449,155</td>
<td style="font-weight: bold; text-align:right">4,504,425</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>318</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,158</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,569,895</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">223,396                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,323,813</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,833</td>
<td style="text-align:right;font-weight:bold;">22,686</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">358,696</td>
<td style="font-weight: bold; text-align:right">3,261</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>307</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">331</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,866,342</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">398,431                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,273,109</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">194,802</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">156,827</td>
<td style="font-weight: bold; text-align:right">2,733</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>366</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,336</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>

In [3]:
table_code.find_all('tr')

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>126,309,685</td>
 <td></td>
 <td>1,630,352</td>
 <td></td>
 <td>122,090,281</td>
 <td>+1,003</td>
 <td>2,589,052</td>
 <td>6,413</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>216,724,187</td>
 <td>+18,459</td>
 <td>1,544,873</td>
 <td>+6</td>
 <td>200,607,206</td>
 <td>+4,932</td>
 <td>14,572,108</td>
 <td>15,649</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>248,938,503</td>
 <td></td>
 <td>2,053,808</td>
 <td></td>
 <td>244,762,390</td>
 <td>+2,996</td>
 <td>2,122,305</td>
 <td>6,362</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>68,600,642</td>
 <td></td>
 <td>1,354,635</td>
 <td></td>
 <td>66,449,498</td>
 <td></td>
 <td>796,509</td>
 <td>10,134</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,182,986</td>
 <td></td>
 <td>27,278</td>
 <td></td>
 <td>14,020,441</td>
 <td></td>
 <td>135,267</td>
 <td>89</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,819,926</td>
 <td></td>
 <td>258,731</td>
 <td></td>
 <td>12,084,339</td>
 <td></td>
 <td>476,856</td>
 <td>548</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>687,576,650</td>
 <td>+18,459</td>
 <td>6,869,692</td>
 <td>+6</td>
 <td>660,014,861</td>
 <td>+8,903</td>
 <td>20,692,097</td>
 <td>39,195</td>
 <td>88,210</td>
 <td>881.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">106,762,797</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,162,403                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">104,699,401</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">900,993</td>
 <td style="font-weight: bold; text-align:right">1,247</td>
 <td style="font-weight: bold; text-align:right">318,880</td>
 <td style="font-weight: bold; text-align:right">3,472</td>
 <td style="font-weight: bold; text-align:right">1,178,666,374</td>
 <td style="font-weight: bold; text-align:right">3,520,453</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>288</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,691</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,960,678</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">531,606                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,392,828</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">36,244</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">31,963</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">927,239,236</td>
 <td style="font-weight: bold; text-align:right">659,191</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,646</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">26</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,007,281</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">166,645                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,720,963</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">119,673</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">610,011</td>
 <td style="font-weight: bold; text-align:right">2,541</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>394</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,825</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,409,620</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">173,307                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,204,800</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">31,513</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">457,892</td>
 <td style="font-weight: bold; text-align:right">2,066</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>484</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">376</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">37,487,971</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">701,833                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">536,977</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">174,076</td>
 <td style="font-weight: bold; text-align:right">3,259</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>307</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,493</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,766,957</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,614                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">71</td>
 <td style="font-weight: bold; text-align:right">268,878</td>
 <td style="font-weight: bold; text-align:right">594</td>
 <td style="font-weight: bold; text-align:right">100,342,320</td>
 <td style="font-weight: bold; text-align:right">799,000</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,683</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,291</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">31,251,203</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,459</td>
 <td style="font-weight: bold; text-align:right;">34,518                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+6</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,959,576</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,939</td>
 <td style="text-align:right;font-weight:bold;">257,109</td>
 <td style="font-weight: bold; text-align:right">141</td>
 <td style="font-weight: bold; text-align:right">608,830</td>
 <td style="font-weight: bold; text-align:right">672</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,487</td><td>3</td>
 <td style="font-weight: bold; text-align:right">360</td>
 <td style="font-weight: bold; text-align:right">0.1</td>
 <td style="font-weight: bold; text-align:right">5,009</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,788,387</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">189,738                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,468,617</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">130,032</td>
 <td style="font-weight: bold; text-align:right">100</td>
 <td style="font-weight: bold; text-align:right">427,932</td>
 <td style="font-weight: bold; text-align:right">3,149</td>
 <td style="font-weight: bold; text-align:right">271,449,155</td>
 <td style="font-weight: bold; text-align:right">4,504,425</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>318</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,158</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,569,895</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">223,396                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,323,813</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,833</td>
 <td style="text-align:right;font-weight:bold;">22,686</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">358,696</td>
 <td style="font-weight: bold; text-align:right">3,261</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>307</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">331</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">22,866,342</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">398,431                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,273,109</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">194,802</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">156,827</td>
 <td style="font-weight: bold; text-align:right">2,733</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->

In [26]:
tr_tags= table_code.find_all('tr')
tr_tags[0].text

'\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\nNew Cases/1M pop\nNew Deaths/1M pop\nActive Cases/1M pop\n'

In [36]:
tr_tags= table_code.find_all('tr')
tr_tags[1].text

'\n\n\nNorth America\n\n126,309,685\n\n1,630,352\n\n122,090,281\n+1,003\n2,589,052\n6,413\n\n\n\n\n\nNorth America\n\n\n\n\n\n\n\n\n\n\n'

In [4]:
tr_tags = table_code.find_all('tr')
for i in tr_tags:
    print(i.text)

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl
New Cases/1M pop
New Deaths/1M pop
Active Cases/1M pop




North America

126,309,685

1,630,352

122,090,281
+1,003
2,589,052
6,413





North America














Asia

216,724,187
+18,459
1,544,873
+6
200,607,206
+4,932
14,572,108
15,649





Asia














Europe

248,938,503

2,053,808

244,762,390
+2,996
2,122,305
6,362





Europe














South America

68,600,642

1,354,635

66,449,498

796,509
10,134





South America














Oceania

14,182,986

27,278

14,020,441

135,267
89





Australia/Oceania














Africa

12,819,926

258,731

12,084,339

476,856
548





Africa
















721

15

706

0
0



















World
687,576,650
+18,459
6,869,692
+6
660,014,861
+8,903
20,692,097
39,195
88,210
881.3



All












1
USA
106,762,797

1,162,403

104,699,401

900,993
1,247
318,880
3,472
1,178,666,374
3,520,453
334,805,269
North America

32880


2,691


2
India
44,960,678

531,606

44,392,828

36,244
N/A
31,963
378
927,239,236
659,191
1,406,631,776
Asia

312,6462


26


3
France
40,007,281

166,645

39,720,963

119,673
869
610,011
2,541
271,490,188
4,139,547
65,584,518
Europe

23940


1,825


4
Germany
38,409,620

173,307

38,204,800

31,513
N/A
457,892
2,066
122,332,384
1,458,359
83,883,596
Europe

24841


376


5
Brazil
37,487,971

701,833

36,249,161

536,977
N/A
174,076
3,259
63,776,166
296,146
215,353,593
South America

63073


2,493


6
Japan
33,766,957

74,614

N/A
N/A
N/A
71
268,878
594
100,342,320
799,000
125,584,838
Asia

41,6831


95,291


7
S. Korea
31,251,203
+18,459
34,518
+6
30,959,576
+4,939
257,109
141
608,830
672
15,804,065
307,892
51,329,899
Asia

21,4873
360
0.1
5,009


8
Italy
25,788,387

189,738

25,468,617

130,032
100
427,932
3,149
271,449,155
4,504,425
60,262,770
Europe

23180


2,158


9
UK
24,569,895

223,396

24,323,813
+1,833
22,686
N/A
358,696
3,261
522,526,476
7,628,357
68,497,907
Europe

33070


331


10
Russia
22,866,342

398,431

22,273,109

194,802
N/A
156,827
2,733
273,400,000
1,875,095
145,805,947
Europe

63661


1,336


11
Turkey
17,232,066

102,174

N/A
N/A
N/A

201,399
1,194
162,743,369
1,902,052
85,561,976
Asia

58371


4,024


12
Spain
13,825,052

120,715

13,665,628

38,709
231
295,918
2,584
471,036,328
10,082,298
46,719,142
Europe

33870


829


13
Vietnam
11,567,728

43,195

10,624,841

899,692
130
116,901
437
85,826,548
867,342
98,953,541
Asia

92,2911


9,092


14
Australia
11,441,894

20,272

11,394,719

26,903
61
438,912
778
78,835,048
3,024,116
26,068,792
Australia/Oceania

21,2860


1,032


15
Taiwan
10,239,998

19,005

10,220,993

0

428,656
796
30,742,304
1,286,903
23,888,595
Asia

21,2571





16
Argentina
10,044,957

130,472

9,914,485

0
363
218,320
2,836
35,716,069
776,264
46,010,234
South America

53531





17
Netherlands
8,610,372

22,992

8,587,380
+579
0
53
500,270
1,336
25,984,435
1,509,718
17,211,447
Europe

27491





18
Iran
7,607,744

146,058

7,342,490

119,196
407
88,439
1,698
55,353,767
643,478
86,022,837
Asia

115892


1,386


19
Mexico
7,587,643

333,913

6,833,884

419,846
N/A
57,673
2,538
19,930,737
151,492
131,562,772
North America

173947


3,191


20
Indonesia
6,782,048

161,384

6,603,711

16,953
N/A
24,297
578
114,158,919
408,975
279,134,505
Asia

411,7302


61


21
Poland
6,514,251

119,557

5,335,940

1,058,754
648
172,610
3,168
38,672,987
1,024,727
37,739,785
Europe

63161


28,054


22
Colombia
6,365,262

142,722

6,187,494

35,046
342
123,567
2,771
36,951,507
717,327
51,512,762
South America

83611


680


23
Austria
6,067,554

22,405

6,035,469

9,680
55
669,212
2,471
211,273,524
23,302,116
9,066,710
Europe

14050


1,068


24
Greece
6,018,544

36,754

5,960,580

21,210
115
583,382
3,563
102,228,365
9,909,078
10,316,637
Europe

22810


2,056


25
Portugal
5,581,619

26,575

5,550,008

5,036
61
550,425
2,621
46,082,209
4,544,341
10,140,570
Europe

23820


497


26
Ukraine
5,529,459

112,128

5,389,891

27,440

128,020
2,596
32,603,805
754,855
43,192,122
Europe

83851


635


27
Chile
5,284,719

64,497

5,219,820

402
44
274,528
3,350
49,432,422
2,567,892
19,250,195
South America

42980


21


28
Malaysia
5,071,840

37,020

5,020,529

14,291
29
152,853
1,116
68,347,420
2,059,832
33,181,072
Asia

78960


431


29
Israel
4,822,896

12,500

4,798,473

11,923
21
517,145
1,340
41,373,364
4,436,346
9,326,000
Asia

27460


1,278


30
Belgium
4,793,425

34,237

4,746,904
+861
12,284
43
410,808
2,934
37,018,657
3,172,590
11,668,278
Europe

23410


1,053


31
DPRK
4,772,813

74

4,772,739

0

183,636
3


25,990,679
Asia

5351,225





32
Thailand
4,732,301

33,957

4,692,636

5,708
N/A
67,529
485
17,270,775
246,450
70,078,203
Asia

152,0644


81


33
Canada
4,641,301

52,247

4,585,040
+1,003
4,014
99
120,904
1,361
66,343,123
1,728,207
38,388,419
North America

87351


105


34
Czechia
4,640,543

42,774

4,595,388

2,381
10
432,210
3,984
57,181,753
5,325,780
10,736,784
Europe

22510


222


35
Peru
4,503,222

220,196

4,279,159

3,867
26
133,689
6,537
38,548,796
1,144,417
33,684,208
South America

71531


115


36
Switzerland
4,402,438

14,452

4,383,180

4,806
39
501,780
1,647
23,833,472
2,716,487
8,773,637
Europe

26070


548


37
Philippines
4,096,335

66,444

4,022,326

7,565
162
36,409
591
35,037,470
311,419
112,508,994
Asia

271,6933


67


38
South Africa
4,076,463

102,595

3,912,506

61,362
192
67,095
1,689
26,795,090
441,027
60,756,135
Africa

155922


1,010


39
Romania
3,393,902

68,089

3,314,667

11,146
128
178,332
3,578
27,242,332
1,431,446
19,031,335
Europe

62801


586


40
Denmark
3,180,726

8,572

3,171,359

795
19
545,116
1,469
129,268,444
22,154,165
5,834,950
Europe

26810


136


41
Hong Kong
2,892,450

13,563

2,871,114

7,773
28
380,370
1,784
76,127,725
10,011,143
7,604,299
Asia

35610


1,022


42
Sweden
2,707,189

24,141

2,678,950

4,098
8
264,918
2,362
19,500,873
1,908,301
10,218,971
Europe

44231


401


43
Serbia
2,536,159

18,022

2,509,836

8,301
15
293,095
2,083
12,806,989
1,480,061
8,653,016
Europe

34801


959


44
Iraq
2,465,545

25,375

2,439,497

673
21
58,474
602
19,544,451
463,523
42,164,965
Asia

171,6622


16


45
Singapore
2,340,779

1,727

2,149,583

189,469
2
393,835
291
24,756,666
4,165,302
5,943,546
Asia

33,4420


31,878


46
New Zealand
2,324,094

4,154

2,310,320

9,620

474,479
848
7,768,604
1,586,011
4,898,203
Australia/Oceania

21,1791


1,964


47
Hungary
2,201,355

48,846

2,148,647

3,862
13
229,158
5,085
11,394,556
1,186,160
9,606,259
Europe

41971


402


48
Bangladesh
2,038,250

29,446

1,998,448

10,356
N/A
12,141
175
15,254,399
90,862
167,885,689
Asia

825,70111


62


49
Slovakia
1,866,470

21,167

1,845,061
+33
242
18
341,832
3,877
7,427,231
1,360,251
5,460,193
Europe

32581


44


50
Georgia
1,840,187

17,059

1,776,548

46,580

463,671
4,298
16,920,079
4,263,340
3,968,738
Asia

22330


11,737


51
Jordan
1,746,997

14,122

1,731,007

1,868
59
169,597
1,371
17,201,885
1,669,945
10,300,869
Asia

67291


181


52
Ireland
1,710,625

8,866

1,699,569

2,190
19
340,748
1,766
13,083,449
2,606,161
5,020,199
Europe

35660


436


53
Pakistan
1,580,801

30,658

1,538,689

11,454
8
6,888
134
30,571,377
133,215
229,488,994
Asia

1457,4858


50


54
Norway
1,483,454

5,213

1,477,213

1,028
20
269,162
946
11,002,430
1,996,315
5,511,370
Europe

41,0571


187


55
Finland
1,475,378

9,373

1,459,986

6,019
21
265,597
1,687
12,090,288
2,176,485
5,554,960
Europe

45930


1,084


56
Kazakhstan
1,411,768

13,848

1,383,020

14,900
24
73,510
721
11,575,012
602,707
19,205,043
Asia

141,3872


776


57
Slovenia
1,343,364

7,100

1,328,006

8,258
8
646,459
3,417
2,847,701
1,370,382
2,078,034
Europe

22931


3,974


58
Lithuania
1,318,786

9,669

1,307,212

1,905
2
495,466
3,633
10,439,469
3,922,094
2,661,708
Europe

22750


716


59
Bulgaria
1,305,030

38,339

1,264,067

2,624
30
190,666
5,601
11,190,426
1,634,928
6,844,597
Europe

51791


383


60
Morocco
1,273,463

16,297

1,256,151

1,015
3
33,714
431
13,001,033
344,191
37,772,756
Africa

302,3183


27


61
Croatia
1,272,886

18,180

1,253,558

1,148
6
313,574
4,479
5,582,393
1,375,215
4,059,286
Europe

32231


283


62
Guatemala
1,248,823

20,196

1,227,381

1,246
5
67,199
1,087
7,235,362
389,332
18,584,039
North America

159203


67


63
Lebanon
1,236,971

10,904

1,087,587

138,480
74
185,041
1,631
4,795,578
717,380
6,684,849
Asia

56131


20,716


64
Costa Rica
1,228,659

9,351

860,711

358,597
52
237,085
1,804
4,659,757
899,158
5,182,354
North America

45541


69,196


65
Bolivia
1,197,458

22,377

1,166,413

8,668
220
99,849
1,866
2,705,422
225,590
11,992,656
South America

105364


723


66
Tunisia
1,152,877

29,398

N/A
N/A
N/A
44
95,701
2,440
5,010,521
415,926
12,046,656
Africa

104102


1,119


67
Cuba
1,113,374

8,530

1,104,696

148
2
98,479
754
14,345,279
1,268,859
11,305,652
North America

101,3251


13


68
UAE
1,063,002

2,349

1,046,765

13,888

105,438
233
200,369,120
19,874,369
10,081,785
Asia

94,2920


1,378


69
Ecuador
1,061,100

36,019

1,023,510

1,571
759
58,581
1,989
3,082,403
170,173
18,113,361
South America

175036


87


70
Uruguay
1,037,893

7,625

1,029,835

433
18
296,879
2,181
6,114,822
1,749,083
3,496,016
South America

34581


124


71
Panama
1,037,324

8,621

1,028,182

521
16
233,266
1,939
7,660,443
1,722,623
4,446,964
North America

45161


117


72
Mongolia
1,007,993

2,179

1,005,787

27
192
298,392
645
4,030,048
1,193,000
3,378,078
Asia

31,5501


8


73
Nepal
1,003,064

12,031

990,831

202

33,186
398
6,036,615
199,719
30,225,582
Asia

302,5125


7


74
Belarus
994,037

7,118

985,592

1,327

105,381
755
13,646,641
1,446,722
9,432,800
Europe

91,3251


141


75
Latvia
977,697

6,325

971,095

277
13
528,817
3,421
7,874,100
4,258,948
1,848,837
Europe

22920


150


76
Saudi Arabia
841,348

9,646

827,696

4,006
65
23,472
269
45,476,472
1,268,701
35,844,909
Asia

433,7161


112


77
Azerbaijan
831,460

10,250

820,953

257

80,723
995
7,593,644
737,232
10,300,205
Asia

121,0051


25


78
Paraguay
809,731

19,916

N/A
N/A
N/A
7
110,833
2,726
2,657,506
363,751
7,305,843
South America

93673


12,524


79
Bahrain
720,424

1,562

718,310

552
1
403,829
876
10,833,573
6,072,688
1,783,983
Asia

21,1420


309


80
Sri Lanka
672,188

16,844

655,320

24

31,155
781
6,486,117
300,619
21,575,842
Asia

321,2813


1


81
Kuwait
665,741

2,570

660,237

2,934

151,984
587
8,455,743
1,930,391
4,380,326
Asia

71,7041


670


82
Dominican Republic
661,045

4,384

644,785

11,876
4
59,789
397
3,740,928
338,350
11,056,370
North America

172,5223


1,074


83
Cyprus
658,450

1,354

655,550

1,546
60
538,219
1,107
9,640,118
7,879,860
1,223,387
Asia

29040


1,264


84
Myanmar
635,452

19,492

614,998

962

11,506
353
10,407,809
188,455
55,227,143
Asia

872,8335


17


85
Palestine
621,008

5,404

615,445

159
17
116,173
1,011
3,078,533
575,907
5,345,541
Asia

99892


30


86
Moldova
620,419

12,113

504,142

104,164
49
154,596
3,018
3,216,305
801,437
4,013,171
Europe

63311


25,956


87
Estonia
618,200

3,001

524,990

90,209
3
467,657
2,270
3,706,919
2,804,214
1,321,910
Europe

24400


68,241


88
Venezuela
552,695

5,856

546,537

302
31
18,885
200
3,359,014
114,771
29,266,991
South America

534,9989


10


89
Egypt
515,970

24,613

442,182

49,175
122
4,860
232
3,693,367
34,792
106,156,692
Africa

2064,31329


463


90
Qatar
509,440

690

507,534

1,216
32
170,958
232
4,065,369
1,364,257
2,979,915
Asia

64,3191


408


91
Libya
507,252

6,437

500,813

2

72,045
914
2,483,848
352,782
7,040,745
Africa

141,0943


0.3


92
Ethiopia
500,847

7,574

487,977

5,296
1
4,146
63
5,543,560
45,886
120,812,698
Africa

24115,95122


44


93
Réunion
486,588

921

418,572

67,095
10
535,854
1,014
1,603,660
1,766,027
908,061
Africa

29861


73,888


94
Honduras
472,533

11,112

N/A
N/A
N/A
105
46,230
1,087
1,652,947
161,717
10,221,247
North America

229206


32,176


95
Armenia
449,062

8,747

435,162

5,153

151,099
2,943
3,242,901
1,091,164
2,971,966
Asia

73401


1,734


96
Bosnia and Herzegovina
402,848

16,337

379,084

7,427

123,979
5,028
1,884,721
580,036
3,249,317
Europe

81992


2,286


97
Oman
399,449

4,628

384,669

10,152
2
75,028
869
25,000,000
4,695,724
5,323,993
Asia

131,1500


1,907


98
North Macedonia
348,142

9,673

337,068

1,401

167,271
4,648
2,226,216
1,069,626
2,081,304
Europe

62151


673


99
Zambia
343,910

4,058

339,811

41

17,663
208
4,033,092
207,141
19,470,234
Africa

574,7985


2


100
Kenya
343,060

5,688

337,309

63
1
6,103
101
3,967,062
70,569
56,215,221
Africa

1649,88314


1


101
Albania
334,726

3,602

329,428

1,696

116,777
1,257
1,941,032
677,173
2,866,374
Europe

97961


592


102
Botswana
329,852

2,801

327,056

-5
1
135,121
1,147
2,026,898
830,300
2,441,162
Africa

78721


-2.05


103
Luxembourg
297,757

1,133

288,991

7,633

463,528
1,764
4,412,567
6,869,188
642,371
Europe

25670


11,883


104
Montenegro
291,602

2,826

288,184

592
6
464,371
4,500
2,749,797
4,379,006
627,950
Europe

22220


943


105
Brunei
288,051

225

243,601

44,225
3
646,679
505
717,784
1,611,437
445,431
Asia

21,9801


99,286


106
Algeria
271,745

6,881

182,978

81,886

5,992
152
230,960
5,093
45,350,148
Africa

1676,591196


1,806


107
Nigeria
266,675

3,155

259,953

3,567
11
1,230
15
5,708,974
26,339
216,746,934
Africa

81368,70038


16


108
Zimbabwe
264,685

5,686

258,888

111
12
17,264
371
2,525,756
164,744
15,331,428
Africa

582,6966


7


109
Uzbekistan
253,009

1,637

241,486

9,886
23
7,359
48
1,377,915
40,077
34,382,084
Asia

13621,00325


288


110
Mozambique
233,417

2,243

228,805

2,369
11
7,054
68
1,371,127
41,437
33,089,461
Africa

14214,75224


72


111
Martinique
229,900

1,100

N/A
N/A
N/A
12
614,563
2,940
828,928
2,215,870
374,087
North America

23400


611,344


112
Laos
218,081

758

N/A
N/A
N/A

29,151
101
1,233,207
164,845
7,481,023
Asia

349,8696


28,026


113
Afghanistan
216,396

7,896

194,073

14,427
45
5,310
194
1,237,975
30,376
40,754,388
Asia

1885,16133


354


114
Iceland
209,191

229

N/A
N/A
N/A
2
605,661
663
1,996,384
5,780,036
345,393
Europe

21,5080


385,871


115
Kyrgyzstan
206,888

2,991

196,406

7,491
131
30,749
445
1,907,195
283,460
6,728,271
Asia

332,2504


1,113


116
Guadeloupe
202,653

1,017

N/A
N/A
N/A
19
506,894
2,544
938,039
2,346,306
399,794
North America

23930


498,722


117
El Salvador
201,785

4,230

179,410

18,145
8
30,805
646
2,610,114
398,467
6,550,389
North America

321,5493


2,770


118
Trinidad and Tobago
191,496

4,390

187,078

28
8
136,143
3,121
913,289
649,295
1,406,585
North America

73202


20


119
Maldives
186,435

313

163,687

22,435
25
344,621
579
2,213,831
4,092,223
540,985
Asia

31,7280


41,471


120
Ghana
171,657

1,462

170,161

34
2
5,299
45
2,536,496
78,298
32,395,450
Africa

18922,15813


1


121
Namibia
171,222

4,090

167,099

33

65,008
1,553
1,062,663
403,460
2,633,874
Africa

156442


13


122
Uganda
170,647

3,632

100,431

66,584
3
3,523
75
3,012,408
62,198
48,432,863
Africa

28413,33516


1,375


123
Jamaica
154,825

3,536

102,851

48,438

51,866
1,185
1,183,986
396,633
2,985,094
North America

198443


16,227


124
Cambodia
138,733

3,056

135,675

2

8,081
178
3,091,420
180,062
17,168,639
Asia

1245,6186


0.1


125
Rwanda
133,194

1,468

131,647

79

9,793
108
6,021,981
442,778
13,600,464
Africa

1029,2652


6


126
Cameroon
124,983

1,971

122,807

205
13
4,478
71
1,751,774
62,762
27,911,548
Africa

22314,16116


7


127
Malta
118,524

835

117,064

625
4
266,926
1,880
2,136,024
4,810,507
444,033
Europe

45320


1,408


128
Barbados
107,566

589

106,971

6

373,463
2,045
801,451
2,782,594
288,023
North America

34890


21


129
Angola
105,384

1,934

103,419

31

3,009
55
1,499,795
42,818
35,027,343
Africa

33218,11123


0.9


130
Channel Islands
101,717

228

101,321

168

576,421
1,292
1,252,808
7,099,551
176,463
Europe

27740


952


131
French Guiana
98,041

420

11,254

86,367
6
312,065
1,337
651,257
2,072,951
314,169
South America

37480


274,906


132
DRC
96,212

1,464

84,489

10,259

1,010
15
846,704
8,890
95,240,792
Africa

99065,055112


108


133
Senegal
88,997

1,971

87,024

2

5,041
112
1,146,543
64,946
17,653,671
Africa

1988,95715


0.1


134
Malawi
88,728

2,686

85,651

391
67
4,397
133
624,784
30,959
20,180,839
Africa

2277,51332


19


135
Ivory Coast
88,326

834

87,489

3

3,184
30
1,689,707
60,907
27,742,298
Africa

31433,26416


0.1


136
Suriname
82,495

1,404

N/A
N/A
N/A

138,222
2,352
241,666
404,915
596,831
South America

74252


52,502


137
New Caledonia
79,922

314

79,605

3
9
274,726
1,079
98,964
340,182
290,915
Australia/Oceania

49263


10


138
French Polynesia
78,488

649

N/A
N/A
N/A
7
276,207
2,284


284,164
Australia/Oceania

4438


156,033


139
Eswatini
74,627

1,425

73,116

86

62,986
1,203
1,048,704
885,119
1,184,817
Africa

168311


73


140
Guyana
73,168

1,298

71,827

43

92,146
1,635
728,813
917,848
794,045
South America

116121


54


141
Belize
70,782

688

70,085

9
6
171,722
1,669
576,016
1,397,453
412,190
North America

65991


22


142
Fiji
68,921

883

67,029

1,009

75,782
971
670,903
737,689
909,466
Australia/Oceania

131,0301


1,109


143
Madagascar
68,236

1,424

66,786

26

2,339
49
530,005
18,164
29,178,077
Africa

42820,49055


0.9


144
Sudan
63,993

5,046

58,640

307

1,391
110
562,941
12,240
45,992,020
Africa

7199,11582


7


145
Mauritania
63,715

997

62,471

247

12,998
203
1,009,957
206,030
4,901,981
Africa

774,9175


50


146
Cabo Verde
63,574

413

62,999

162
23
111,990
728
401,622
707,482
567,678
Africa

91,3751


285


147
Bhutan
62,666

21

61,564

1,081

79,531
27
2,303,734
2,923,739
787,941
Asia

1337,5210


1,372


148
Syria
57,508

3,164

54,344

0

2,970
163
146,269
7,553
19,364,809
Asia

3376,120132





149
Burundi
53,740

38

53,569

133

4,257
3
345,742
27,386
12,624,840
Africa

235332,23337


11


150
Seychelles
50,937

172

50,750

15

512,311
1,730


99,426
Africa

2578


151


151
Gabon
48,981

306

48,674

1

21,008
131
1,621,909
695,641
2,331,533
Africa

487,6191


0.4


152
Andorra
47,974

165

47,563

246
14
619,315
2,130
249,838
3,225,256
77,463
Europe

24690


3,176


153
Papua New Guinea
46,842

670

43,982

2,190
7
5,041
72
249,149
26,813
9,292,169
Australia/Oceania

19813,86937


236


154
Curaçao
45,986

295

44,720

971
3
277,812
1,782
496,693
3,000,640
165,529
North America

45610


5,866


155
Aruba
44,114

236

42,438

1,440
2
409,947
2,193
177,885
1,653,068
107,609
North America

24561


13,382


156
Tanzania
42,973

846

N/A
N/A
N/A
7
679
13


63,298,550
Africa

1,47374,821


663


157
Mauritius
42,152

1,045

40,357

750

33,067
820
358,675
281,374
1,274,727
Africa

301,2204


588


158
Mayotte
42,027

188

N/A
N/A
N/A

146,815
657
176,919
618,038
286,259
Africa

71,5232


135,804


159
Togo
39,487

290

39,184

13

4,549
33
810,964
93,420
8,680,837
Africa

22029,93411


1


160
Guinea
38,462

467

37,757

238
8
2,774
34
660,107
47,607
13,865,691
Africa

36129,69121


17


161
Bahamas
38,084

844

36,366

874
1
95,087
2,107
257,839
643,767
400,516
North America

114752


2,182


162
Isle of Man
38,008

116

N/A
N/A
N/A

443,335
1,353
150,753
1,758,422
85,732
Europe

27391


129,450


163
Lesotho
34,790

723

25,980

8,087

15,990
332
431,221
198,199
2,175,699
Africa

633,0095


3,717


164
Faeroe Islands
34,658

28

N/A
N/A
N/A
5
703,959
569
778,000
15,802,409
49,233
Europe

11,7580


547,133


165
Haiti
34,228

860

33,342

26

2,930
74
132,422
11,337
11,680,283
North America

34113,58288


2


166
Mali
33,144

743

32,324

77

1,543
35
803,454
37,416
21,473,764
Africa

64828,90127


4


167
Cayman Islands
31,472

37

8,553

22,882
1
467,797
550
222,773
3,311,280
67,277
North America

21,8180


340,116


168
Saint Lucia
30,052

409

29,095

548

162,344
2,209
210,983
1,139,752
185,113
North America

64531


In [5]:
tr_tags = table_code.find_all('tr')
#for i in tr_tags:
#    print(i.text)
tr_tags[0].text.split('\n')

['',
 '#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop',
 '']

In [6]:
tr_tags = table_code.find_all('tr')
for i in tr_tags:
    print(i.text.split('\n'))

['', '#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/', '1M pop', '', 'Population', 'Continent', '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl', 'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop', '']
['', '', '', 'North America', '', '126,309,685', '', '1,630,352', '', '122,090,281', '+1,003', '2,589,052', '6,413', '', '', '', '', '', 'North America', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'Asia', '', '216,724,187', '+18,459', '1,544,873', '+6', '200,607,206', '+4,932', '14,572,108', '15,649', '', '', '', '', '', 'Asia', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'Europe', '', '248,938,503', '', '2,053,808', '', '244,762,390', '+2,996', '2,122,305', '6,362', '', '', '', '', '', 'Europe', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'South America', '', '68,600,642', '', '1,354,635', '', '66,449,498', '', '796,509', '10,134', '', '', '', '', '', 'South America', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'Oceania', '', '14,182,986', '', '27,278', '', '14,020,441', '', '135,267', '89', '', '', '', '', '', 'Australia/Oceania', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'Africa', '', '12,819,926', '', '258,731', '', '12,084,339', '', '476,856', '548', '', '', '', '', '', 'Africa', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '721', '', '15', '', '706', '', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', 'World', '687,576,650', '+18,459', '6,869,692', '+6', '660,014,861', '+8,903', '20,692,097', '39,195', '88,210', '881.3', '', '', '', 'All', '', '', '', '', '', '', '', '', '', '', '']
['', '1', 'USA', '106,762,797', '', '1,162,403                                ', '', '104,699,401', '', '900,993', '1,247', '318,880', '3,472', '1,178,666,374', '3,520,453', '334,805,269 ', 'North America', '', '32880', '', '', '2,691', '']
['', '2', 'India', '44,960,678', '', '531,606                                ', '', '44,392,828', '', '36,244', 'N/A', '31,963', '378', '927,239,236', '659,191', '1,406,631,776 ', 'Asia', '', '312,6462', '', '', '26', '']
['', '3', 'France', '40,007,281', '', '166,645                                ', '', '39,720,963', '', '119,673', '869', '610,011', '2,541', '271,490,188', '4,139,547', '65,584,518 ', 'Europe', '', '23940', '', '', '1,825', '']
['', '4', 'Germany', '38,409,620', '', '173,307                                ', '', '38,204,800', '', '31,513', 'N/A', '457,892', '2,066', '122,332,384', '1,458,359', '83,883,596 ', 'Europe', '', '24841', '', '', '376', '']
['', '5', 'Brazil', '37,487,971', '', '701,833                                ', '', '36,249,161', '', '536,977', 'N/A', '174,076', '3,259', '63,776,166', '296,146', '215,353,593 ', 'South America', '', '63073', '', '', '2,493', '']
['', '6', 'Japan', '33,766,957', '', '74,614                                ', '', 'N/A', 'N/A', 'N/A', '71', '268,878', '594', '100,342,320', '799,000', '125,584,838 ', 'Asia', '', '41,6831', '', '', '95,291', '']
['', '7', 'S. Korea', '31,251,203', '+18,459', '34,518                                ', '+6', '30,959,576', '+4,939', '257,109', '141', '608,830', '672', '15,804,065', '307,892', '51,329,899 ', 'Asia', '', '21,4873', '360', '0.1', '5,009', '']
['', '8', 'Italy', '25,788,387', '', '189,738                                ', '', '25,468,617', '', '130,032', '100', '427,932', '3,149', '271,449,155', '4,504,425', '60,262,770 ', 'Europe', '', '23180', '', '', '2,158', '']
['', '9', 'UK', '24,569,895', '', '223,396                                ', '', '24,323,813', '+1,833', '22,686', 'N/A', '358,696', '3,261', '522,526,476', '7,628,357', '68,497,907 ', 'Europe', '', '33070', '', '', '331', '']
['', '10', 'Russia', '22,866,342', '', '398,431                                ', '', '22,273,109', '', '194,802', 'N/A', '156,827', '2,733', '273,400,000', '1,875,095', '145,805,947 ', 'Europe', '', '63661', '', '', '1,336', '']
['', '11', 'Turkey', '17,232,066', '', '102,174                                ', '', 'N/A', 'N/A', 'N/A', '', '201,399', '1,194', '162,743,369', '1,902,052', '85,561,976 ', 'Asia', '', '58371', '', '', '4,024', '']
['', '12', 'Spain', '13,825,052', '', '120,715                                ', '', '13,665,628', '', '38,709', '231', '295,918', '2,584', '471,036,328', '10,082,298', '46,719,142 ', 'Europe', '', '33870', '', '', '829', '']
['', '13', 'Vietnam', '11,567,728', '', '43,195                                ', '', '10,624,841', '', '899,692', '130', '116,901', '437', '85,826,548', '867,342', '98,953,541 ', 'Asia', '', '92,2911', '', '', '9,092', '']
['', '14', 'Australia', '11,441,894', '', '20,272                                ', '', '11,394,719', '', '26,903', '61', '438,912', '778', '78,835,048', '3,024,116', '26,068,792 ', 'Australia/Oceania', '', '21,2860', '', '', '1,032', '']
['', '15', 'Taiwan', '10,239,998', '', '19,005                                ', '', '10,220,993', '', '0', '', '428,656', '796', '30,742,304', '1,286,903', '23,888,595 ', 'Asia', '', '21,2571', '', '', '', '']
['', '16', 'Argentina', '10,044,957', '', '130,472                                ', '', '9,914,485', '', '0', '363', '218,320', '2,836', '35,716,069', '776,264', '46,010,234 ', 'South America', '', '53531', '', '', '', '']
['', '17', 'Netherlands', '8,610,372', '', '22,992                                ', '', '8,587,380', '+579', '0', '53', '500,270', '1,336', '25,984,435', '1,509,718', '17,211,447 ', 'Europe', '', '27491', '', '', '', '']
['', '18', 'Iran', '7,607,744', '', '146,058                                ', '', '7,342,490', '', '119,196', '407', '88,439', '1,698', '55,353,767', '643,478', '86,022,837 ', 'Asia', '', '115892', '', '', '1,386', '']
['', '19', 'Mexico', '7,587,643', '', '333,913                                ', '', '6,833,884', '', '419,846', 'N/A', '57,673', '2,538', '19,930,737', '151,492', '131,562,772 ', 'North America', '', '173947', '', '', '3,191', '']
['', '20', 'Indonesia', '6,782,048', '', '161,384                                ', '', '6,603,711', '', '16,953', 'N/A', '24,297', '578', '114,158,919', '408,975', '279,134,505 ', 'Asia', '', '411,7302', '', '', '61', '']
['', '21', 'Poland', '6,514,251', '', '119,557                                ', '', '5,335,940', '', '1,058,754', '648', '172,610', '3,168', '38,672,987', '1,024,727', '37,739,785 ', 'Europe', '', '63161', '', '', '28,054', '']
['', '22', 'Colombia', '6,365,262', '', '142,722                                ', '', '6,187,494', '', '35,046', '342', '123,567', '2,771', '36,951,507', '717,327', '51,512,762 ', 'South America', '', '83611', '', '', '680', '']
['', '23', 'Austria', '6,067,554', '', '22,405                                ', '', '6,035,469', '', '9,680', '55', '669,212', '2,471', '211,273,524', '23,302,116', '9,066,710 ', 'Europe', '', '14050', '', '', '1,068', '']
['', '24', 'Greece', '6,018,544', '', '36,754                                ', '', '5,960,580', '', '21,210', '115', '583,382', '3,563', '102,228,365', '9,909,078', '10,316,637 ', 'Europe', '', '22810', '', '', '2,056', '']
['', '25', 'Portugal', '5,581,619', '', '26,575                                ', '', '5,550,008', '', '5,036', '61', '550,425', '2,621', '46,082,209', '4,544,341', '10,140,570 ', 'Europe', '', '23820', '', '', '497', '']
['', '26', 'Ukraine', '5,529,459', '', '112,128                                ', '', '5,389,891', '', '27,440', '', '128,020', '2,596', '32,603,805', '754,855', '43,192,122 ', 'Europe', '', '83851', '', '', '635', '']
['', '27', 'Chile', '5,284,719', '', '64,497                                ', '', '5,219,820', '', '402', '44', '274,528', '3,350', '49,432,422', '2,567,892', '19,250,195 ', 'South America', '', '42980', '', '', '21', '']
['', '28', 'Malaysia', '5,071,840', '', '37,020                                ', '', '5,020,529', '', '14,291', '29', '152,853', '1,116', '68,347,420', '2,059,832', '33,181,072 ', 'Asia', '', '78960', '', '', '431', '']
['', '29', 'Israel', '4,822,896', '', '12,500                                ', '', '4,798,473', '', '11,923', '21', '517,145', '1,340', '41,373,364', '4,436,346', '9,326,000 ', 'Asia', '', '27460', '', '', '1,278', '']
['', '30', 'Belgium', '4,793,425', '', '34,237                                ', '', '4,746,904', '+861', '12,284', '43', '410,808', '2,934', '37,018,657', '3,172,590', '11,668,278 ', 'Europe', '', '23410', '', '', '1,053', '']
['', '31', 'DPRK', '4,772,813', '', '74                                ', '', '4,772,739', '', '0', '', '183,636', '3', '', '', '25,990,679 ', 'Asia', '', '5351,225', '', '', '', '']
['', '32', 'Thailand', '4,732,301', '', '33,957                                ', '', '4,692,636', '', '5,708', 'N/A', '67,529', '485', '17,270,775', '246,450', '70,078,203 ', 'Asia', '', '152,0644', '', '', '81', '']
['', '33', 'Canada', '4,641,301', '', '52,247                                ', '', '4,585,040', '+1,003', '4,014', '99', '120,904', '1,361', '66,343,123', '1,728,207', '38,388,419 ', 'North America', '', '87351', '', '', '105', '']
['', '34', 'Czechia', '4,640,543', '', '42,774                                ', '', '4,595,388', '', '2,381', '10', '432,210', '3,984', '57,181,753', '5,325,780', '10,736,784 ', 'Europe', '', '22510', '', '', '222', '']
['', '35', 'Peru', '4,503,222', '', '220,196                                ', '', '4,279,159', '', '3,867', '26', '133,689', '6,537', '38,548,796', '1,144,417', '33,684,208 ', 'South America', '', '71531', '', '', '115', '']
['', '36', 'Switzerland', '4,402,438', '', '14,452                                ', '', '4,383,180', '', '4,806', '39', '501,780', '1,647', '23,833,472', '2,716,487', '8,773,637 ', 'Europe', '', '26070', '', '', '548', '']
['', '37', 'Philippines', '4,096,335', '', '66,444                                ', '', '4,022,326', '', '7,565', '162', '36,409', '591', '35,037,470', '311,419', '112,508,994 ', 'Asia', '', '271,6933', '', '', '67', '']
['', '38', 'South Africa', '4,076,463', '', '102,595                                ', '', '3,912,506', '', '61,362', '192', '67,095', '1,689', '26,795,090', '441,027', '60,756,135 ', 'Africa', '', '155922', '', '', '1,010', '']
['', '39', 'Romania', '3,393,902', '', '68,089                                ', '', '3,314,667', '', '11,146', '128', '178,332', '3,578', '27,242,332', '1,431,446', '19,031,335 ', 'Europe', '', '62801', '', '', '586', '']
['', '40', 'Denmark', '3,180,726', '', '8,572                                ', '', '3,171,359', '', '795', '19', '545,116', '1,469', '129,268,444', '22,154,165', '5,834,950 ', 'Europe', '', '26810', '', '', '136', '']
['', '41', 'Hong Kong', '2,892,450', '', '13,563                                ', '', '2,871,114', '', '7,773', '28', '380,370', '1,784', '76,127,725', '10,011,143', '7,604,299 ', 'Asia', '', '35610', '', '', '1,022', '']
['', '42', 'Sweden', '2,707,189', '', '24,141                                ', '', '2,678,950', '', '4,098', '8', '264,918', '2,362', '19,500,873', '1,908,301', '10,218,971 ', 'Europe', '', '44231', '', '', '401', '']
['', '43', 'Serbia', '2,536,159', '', '18,022                                ', '', '2,509,836', '', '8,301', '15', '293,095', '2,083', '12,806,989', '1,480,061', '8,653,016 ', 'Europe', '', '34801', '', '', '959', '']
['', '44', 'Iraq', '2,465,545', '', '25,375                                ', '', '2,439,497', '', '673', '21', '58,474', '602', '19,544,451', '463,523', '42,164,965 ', 'Asia', '', '171,6622', '', '', '16', '']
['', '45', 'Singapore', '2,340,779', '', '1,727                                ', '', '2,149,583', '', '189,469', '2', '393,835', '291', '24,756,666', '4,165,302', '5,943,546 ', 'Asia', '', '33,4420', '', '', '31,878', '']
['', '46', 'New Zealand', '2,324,094', '', '4,154                                ', '', '2,310,320', '', '9,620', '', '474,479', '848', '7,768,604', '1,586,011', '4,898,203 ', 'Australia/Oceania', '', '21,1791', '', '', '1,964', '']
['', '47', 'Hungary', '2,201,355', '', '48,846                                ', '', '2,148,647', '', '3,862', '13', '229,158', '5,085', '11,394,556', '1,186,160', '9,606,259 ', 'Europe', '', '41971', '', '', '402', '']
['', '48', 'Bangladesh', '2,038,250', '', '29,446                                ', '', '1,998,448', '', '10,356', 'N/A', '12,141', '175', '15,254,399', '90,862', '167,885,689 ', 'Asia', '', '825,70111', '', '', '62', '']
['', '49', 'Slovakia', '1,866,470', '', '21,167                                ', '', '1,845,061', '+33', '242', '18', '341,832', '3,877', '7,427,231', '1,360,251', '5,460,193 ', 'Europe', '', '32581', '', '', '44', '']
['', '50', 'Georgia', '1,840,187', '', '17,059                                ', '', '1,776,548', '', '46,580', '', '463,671', '4,298', '16,920,079', '4,263,340', '3,968,738 ', 'Asia', '', '22330', '', '', '11,737', '']
['', '51', 'Jordan', '1,746,997', '', '14,122                                ', '', '1,731,007', '', '1,868', '59', '169,597', '1,371', '17,201,885', '1,669,945', '10,300,869 ', 'Asia', '', '67291', '', '', '181', '']
['', '52', 'Ireland', '1,710,625', '', '8,866                                ', '', '1,699,569', '', '2,190', '19', '340,748', '1,766', '13,083,449', '2,606,161', '5,020,199 ', 'Europe', '', '35660', '', '', '436', '']
['', '53', 'Pakistan', '1,580,801', '', '30,658                                ', '', '1,538,689', '', '11,454', '8', '6,888', '134', '30,571,377', '133,215', '229,488,994 ', 'Asia', '', '1457,4858', '', '', '50', '']
['', '54', 'Norway', '1,483,454', '', '5,213                                ', '', '1,477,213', '', '1,028', '20', '269,162', '946', '11,002,430', '1,996,315', '5,511,370 ', 'Europe', '', '41,0571', '', '', '187', '']
['', '55', 'Finland', '1,475,378', '', '9,373                                ', '', '1,459,986', '', '6,019', '21', '265,597', '1,687', '12,090,288', '2,176,485', '5,554,960 ', 'Europe', '', '45930', '', '', '1,084', '']
['', '56', 'Kazakhstan', '1,411,768', '', '13,848                                ', '', '1,383,020', '', '14,900', '24', '73,510', '721', '11,575,012', '602,707', '19,205,043 ', 'Asia', '', '141,3872', '', '', '776', '']
['', '57', 'Slovenia', '1,343,364', '', '7,100                                ', '', '1,328,006', '', '8,258', '8', '646,459', '3,417', '2,847,701', '1,370,382', '2,078,034 ', 'Europe', '', '22931', '', '', '3,974', '']
['', '58', 'Lithuania', '1,318,786', '', '9,669                                ', '', '1,307,212', '', '1,905', '2', '495,466', '3,633', '10,439,469', '3,922,094', '2,661,708 ', 'Europe', '', '22750', '', '', '716', '']
['', '59', 'Bulgaria', '1,305,030', '', '38,339                                ', '', '1,264,067', '', '2,624', '30', '190,666', '5,601', '11,190,426', '1,634,928', '6,844,597 ', 'Europe', '', '51791', '', '', '383', '']
['', '60', 'Morocco', '1,273,463', '', '16,297                                ', '', '1,256,151', '', '1,015', '3', '33,714', '431', '13,001,033', '344,191', '37,772,756 ', 'Africa', '', '302,3183', '', '', '27', '']
['', '61', 'Croatia', '1,272,886', '', '18,180                                ', '', '1,253,558', '', '1,148', '6', '313,574', '4,479', '5,582,393', '1,375,215', '4,059,286 ', 'Europe', '', '32231', '', '', '283', '']
['', '62', 'Guatemala', '1,248,823', '', '20,196                                ', '', '1,227,381', '', '1,246', '5', '67,199', '1,087', '7,235,362', '389,332', '18,584,039 ', 'North America', '', '159203', '', '', '67', '']
['', '63', 'Lebanon', '1,236,971', '', '10,904                                ', '', '1,087,587', '', '138,480', '74', '185,041', '1,631', '4,795,578', '717,380', '6,684,849 ', 'Asia', '', '56131', '', '', '20,716', '']
['', '64', 'Costa Rica', '1,228,659', '', '9,351                                ', '', '860,711', '', '358,597', '52', '237,085', '1,804', '4,659,757', '899,158', '5,182,354 ', 'North America', '', '45541', '', '', '69,196', '']
['', '65', 'Bolivia', '1,197,458', '', '22,377                                ', '', '1,166,413', '', '8,668', '220', '99,849', '1,866', '2,705,422', '225,590', '11,992,656 ', 'South America', '', '105364', '', '', '723', '']
['', '66', 'Tunisia', '1,152,877', '', '29,398                                ', '', 'N/A', 'N/A', 'N/A', '44', '95,701', '2,440', '5,010,521', '415,926', '12,046,656 ', 'Africa', '', '104102', '', '', '1,119', '']
['', '67', 'Cuba', '1,113,374', '', '8,530                                ', '', '1,104,696', '', '148', '2', '98,479', '754', '14,345,279', '1,268,859', '11,305,652 ', 'North America', '', '101,3251', '', '', '13', '']
['', '68', 'UAE', '1,063,002', '', '2,349                                ', '', '1,046,765', '', '13,888', '', '105,438', '233', '200,369,120', '19,874,369', '10,081,785 ', 'Asia', '', '94,2920', '', '', '1,378', '']
['', '69', 'Ecuador', '1,061,100', '', '36,019                                ', '', '1,023,510', '', '1,571', '759', '58,581', '1,989', '3,082,403', '170,173', '18,113,361 ', 'South America', '', '175036', '', '', '87', '']
['', '70', 'Uruguay', '1,037,893', '', '7,625                                ', '', '1,029,835', '', '433', '18', '296,879', '2,181', '6,114,822', '1,749,083', '3,496,016 ', 'South America', '', '34581', '', '', '124', '']
['', '71', 'Panama', '1,037,324', '', '8,621                                ', '', '1,028,182', '', '521', '16', '233,266', '1,939', '7,660,443', '1,722,623', '4,446,964 ', 'North America', '', '45161', '', '', '117', '']
['', '72', 'Mongolia', '1,007,993', '', '2,179                                ', '', '1,005,787', '', '27', '192', '298,392', '645', '4,030,048', '1,193,000', '3,378,078 ', 'Asia', '', '31,5501', '', '', '8', '']
['', '73', 'Nepal', '1,003,064', '', '12,031                                ', '', '990,831', '', '202', '', '33,186', '398', '6,036,615', '199,719', '30,225,582 ', 'Asia', '', '302,5125', '', '', '7', '']
['', '74', 'Belarus', '994,037', '', '7,118                                ', '', '985,592', '', '1,327', '', '105,381', '755', '13,646,641', '1,446,722', '9,432,800 ', 'Europe', '', '91,3251', '', '', '141', '']
['', '75', 'Latvia', '977,697', '', '6,325                                ', '', '971,095', '', '277', '13', '528,817', '3,421', '7,874,100', '4,258,948', '1,848,837 ', 'Europe', '', '22920', '', '', '150', '']
['', '76', 'Saudi Arabia', '841,348', '', '9,646                                ', '', '827,696', '', '4,006', '65', '23,472', '269', '45,476,472', '1,268,701', '35,844,909 ', 'Asia', '', '433,7161', '', '', '112', '']
['', '77', 'Azerbaijan', '831,460', '', '10,250                                ', '', '820,953', '', '257', '', '80,723', '995', '7,593,644', '737,232', '10,300,205 ', 'Asia', '', '121,0051', '', '', '25', '']
['', '78', 'Paraguay', '809,731', '', '19,916                                ', '', 'N/A', 'N/A', 'N/A', '7', '110,833', '2,726', '2,657,506', '363,751', '7,305,843 ', 'South America', '', '93673', '', '', '12,524', '']
['', '79', 'Bahrain', '720,424', '', '1,562                                ', '', '718,310', '', '552', '1', '403,829', '876', '10,833,573', '6,072,688', '1,783,983 ', 'Asia', '', '21,1420', '', '', '309', '']
['', '80', 'Sri Lanka', '672,188', '', '16,844                                ', '', '655,320', '', '24', '', '31,155', '781', '6,486,117', '300,619', '21,575,842 ', 'Asia', '', '321,2813', '', '', '1', '']
['', '81', 'Kuwait', '665,741', '', '2,570                                ', '', '660,237', '', '2,934', '', '151,984', '587', '8,455,743', '1,930,391', '4,380,326 ', 'Asia', '', '71,7041', '', '', '670', '']
['', '82', 'Dominican Republic', '661,045', '', '4,384                                ', '', '644,785', '', '11,876', '4', '59,789', '397', '3,740,928', '338,350', '11,056,370 ', 'North America', '', '172,5223', '', '', '1,074', '']

In [12]:
final_data = []
tr_tags = table_code.find_all('tr')
for i in tr_tags:
    x = i.text.split('\n')
    if x[1] != "":
        final_data.append(x[1:-1])
#final_data

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop'],
 ['',
  '',
  'North America',
  '',
  '126,309,685',
  '',
  '1,630,352',
  '',
  '122,090,281',
  '+1,003',
  '2,589,052',
  '6,413',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Asia',
  '',
  '216,724,187',
  '+18,459',
  '1,544,873',
  '+6',
  '200,607,206',
  '+4,932',
  '14,572,108',
  '15,649',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Europe',
  '',
  '248,938,503',
  '',
  '2,053,808',
  '',
  '244,762,390',
  '+2,996',
  '2,122,305',
  '6,362',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'South America',
  '',
  '68,600,642',
  '',
  '1,354,635',
  '',
  '66,449,498',
  '',
  '796,509',
  '10,134',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Oceania',
  '',
  '14,182,986',
  '',
  '27,278',
  '',
  '14,020,441',
  '',
  '135,267',
  '89',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Africa',
  '',
  '12,819,926',
  '',
  '258,731',
  '',
  '12,084,339',
  '',
  '476,856',
  '548',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  '',
  '721',
  '',
  '15',
  '',
  '706',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  'World',
  '687,576,650',
  '+18,459',
  '6,869,692',
  '+6',
  '660,014,861',
  '+8,903',
  '20,692,097',
  '39,195',
  '88,210',
  '881.3',
  '',
  '',
  '',
  'All',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['1',
  'USA',
  '106,762,797',
  '',
  '1,162,403                                ',
  '',
  '104,699,401',
  '',
  '900,993',
  '1,247',
  '318,880',
  '3,472',
  '1,178,666,374',
  '3,520,453',
  '334,805,269 ',
  'North America',
  '',
  '32880',
  '',
  '',
  '2,691'],
 ['2',
  'India',
  '44,960,678',
  '',
  '531,606                                ',
  '',
  '44,392,828',
  '',
  '36,244',
  'N/A',
  '31,963',
  '378',
  '927,239,236',
  '659,191',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6462',
  '',
  '',
  '26'],
 ['3',
  'France',
  '40,007,281',
  '',
  '166,645                                ',
  '',
  '39,720,963',
  '',
  '119,673',
  '869',
  '610,011',
  '2,541',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23940',
  '',
  '',
  '1,825'],
 ['4',
  'Germany',
  '38,409,620',
  '',
  '173,307                                ',
  '',
  '38,204,800',
  '',
  '31,513',
  'N/A',
  '457,892',
  '2,066',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24841',
  '',
  '',
  '376'],
 ['5',
  'Brazil',
  '37,487,971',
  '',
  '701,833                                ',
  '',
  '36,249,161',
  '',
  '536,977',
  'N/A',
  '174,076',
  '3,259',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63073',
  '',
  '',
  '2,493'],
 ['6',
  'Japan',
  '33,766,957',
  '',
  '74,614                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '71',
  '268,878',
  '594',
  '100,342,320',
  '799,000',
  '125,584,838 ',
  'Asia',
  '',
  '41,6831',
  '',
  '',
  '95,291'],
 ['7',
  'S. Korea',
  '31,251,203',
  '+18,459',
  '34,518                                ',
  '+6',
  '30,959,576',
  '+4,939',
  '257,109',
  '141',
  '608,830',
  '672',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,4873',
  '360',
  '0.1',
  '5,009'],
 ['8',
  'Italy',
  '25,788,387',
  '',
  '189,738                                ',
  '',
  '25,468,617',
  '',
  '130,032',
  '100',
  '427,932',
  '3,149',
  '271,449,155',
  '4,504,425',
  '60,262,770 ',
  'Europe',
  '',
  '23180',
  '',
  '',
  '2,158'],
 ['9',
  'UK',
  '24,569,895',
  '',
  '223,396                                ',
  '',
  '24,323,813',
  '+1,833',
  '22,686',
  'N/A',
  '358,696',
  '3,261',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33070',
  '',
  '',
  '331'],
 ['10',
  'Russia',
  '22,866,342',
  '',
  '398,431                                ',
  '',
  '22,273,109',
  '',
  '194,802',
  'N/A',
  '156,827',
  '2,733',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63661',
  '',
  '',
  '1,336'],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024'],
 ['12',
  'Spain',
  '13,825,052',
  '',
  '120,715                                ',
  '',
  '13,665,628',
  '',
  '38,709',
  '231',
  '295,918',
  '2,584',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33870',
  '',
  '',
  '829'],
 ['13',
  'Vietnam',
  '11,567,728',
  '',
  '43,195                                ',
  '',
  '10,624,841',
  '',
  '899,692',
  '130',
  '116,901',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2911',
  '',
  '',
  '9,092'],
 ['14',
  'Australia',
  '11,441,894',
  '',
  '20,272                                ',
  '',
  '11,394,719',
  '',
  '26,903',
  '61',
  '438,912',
  '778',
  '78,835,048',
  '3,024,116',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,2860',
  '',
  '',
  '1,032'],
 ['15',
  'Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993',
  '',
  '0',
  '',
  '428,656',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  ''],
 ['16',
  'Argentina',
  '10,044,957',
  '',
  '130,472                                ',
  '',
  '9,914,485',
  '',
  '0',
  '363',
  '218,320',
  '2,836',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  ''],
 ['17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,587,380',
  '+579',
  '0',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  ''],
 ['18',
  'Iran',
  '7,607,744',
  '',
  '146,058                                ',
  '',
  '7,342,490',
  '',
  '119,196',
  '407',
  '88,439',
  '1,698',
  '55,353,767',
  '643,478',
  '86,022,837 ',
  'Asia',
  '',
  '115892',
  '',
  '',
  '1,386'],
 ['19',
  'Mexico',
  '7,587,643',
  '',
  '333,913                                ',
  '',
  '6,833,884',
  '',
  '419,846',
  'N/A',
  '57,673',
  '2,538',
  '19,930,737',
  '151,492',
  '131,562,772 ',
  'North America',
  '',
  '173947',
  '',
  '',
  '3,191'],
 ['20',
  'Indonesia',
  '6,782,048',
  '',
  '161,384                                ',
  '',
  '6,603,711',
  '',
  '16,953',
  'N/A',
  '24,297',
  '578',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7302',
  '',
  '',
  '61'],
 ['21',
  'Poland',
  '6,514,251',
  '',
  '119,557                                ',
  '',
  '5,335,940',
  '',
  '1,058,754',
  '648',
  '172,610',
  '3,168',
  '38,672,987',
  '1,024,727',
  '37,739,785 ',
  'Europe',
  '',
  '63161',
  '',
  '',
  '28,054'],
 ['22',
  'Colombia',
  '6,365,262',
  '',
  '142,722                                ',
  '',
  '6,187,494',
  '',
  '35,046',
  '342',
  '123,567',
  '2,771',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83611',
  '',
  '',
  '680'],
 ['23',
  'Austria',
  '6,067,554',
  '',
  '22,405                                ',
  '',
  '6,035,469',
  '',
  '9,680',
  '55',
  '669,212',
  '2,471',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14050',
  '',
  '',
  '1,068'],
 ['24',
  'Greece',
  '6,018,544',
  '',
  '36,754                                ',
  '',
  '5,960,580',
  '',
  '21,210',
  '115',
  '583,382',
  '3,563',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22810',
  '',
  '',
  '2,056'],
 ['25',
  'Portugal',
  '5,581,619',
  '',
  '26,575                                ',
  '',
  '5,550,008',
  '',
  '5,036',
  '61',
  '550,425',
  '2,621',
  '46,082,209',
  '4,544,341',
  '10,140,570 ',
  'Europe',
  '',
  '23820',
  '',
  '',
  '497'],
 ['26',
  'Ukraine',
  '5,529,459',
  '',
  '112,128                                ',
  '',
  '5,389,891',
  '',
  '27,440',
  '',
  '128,020',
  '2,596',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83851',
  '',
  '',
  '635'],
 ['27',
  'Chile',
  '5,284,719',
  '',
  '64,497                                ',
  '',
  '5,219,820',
  '',
  '402',
  '44',
  '274,528',
  '3,350',
  '49,432,422',
  '2,567,892',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '',
  '',
  '21'],
 ['28',
  'Malaysia',
  '5,071,840',
  '',
  '37,020                                ',
  '',
  '5,020,529',
  '',
  '14,291',
  '29',
  '152,853',
  '1,116',
  '68,347,420',
  '2,059,832',
  '33,181,072 ',
  'Asia',
  '',
  '78960',
  '',
  '',
  '431'],
 ['29',
  'Israel',
  '4,822,896',
  '',
  '12,500                                ',
  '',
  '4,798,473',
  '',
  '11,923',
  '21',
  '517,145',
  '1,340',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27460',
  '',
  '',
  '1,278'],
 ['30',
  'Belgium',
  '4,793,425',
  '',
  '34,237                                ',
  '',
  '4,746,904',
  '+861',
  '12,284',
  '43',
  '410,808',
  '2,934',
  '37,018,657',
  '3,172,590',
  '11,668,278 ',
  'Europe',
  '',
  '23410',
  '',
  '',
  '1,053'],
 ['31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  ''],
 ['32',
  'Thailand',
  '4,732,301',
  '',
  '33,957                                ',
  '',
  '4,692,636',
  '',
  '5,708',
  'N/A',
  '67,529',
  '485',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0644',
  '',
  '',
  '81'],
 ['33',
  'Canada',
  '4,641,301',
  '',
  '52,247                                ',
  '',
  '4,585,040',
  '+1,003',
  '4,014',
  '99',
  '120,904',
  '1,361',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '87351',
  '',
  '',
  '105'],
 ['34',
  'Czechia',
  '4,640,543',
  '',
  '42,774                                ',
  '',
  '4,595,388',
  '',
  '2,381',
  '10',
  '432,210',
  '3,984',
  '57,181,753',
  '5,325,780',
  '10,736,784 ',
  'Europe',
  '',
  '22510',
  '',
  '',
  '222'],
 ['35',
  'Peru',
  '4,503,222',
  '',
  '220,196                                ',
  '',
  '4,279,159',
  '',
  '3,867',
  '26',
  '133,689',
  '6,537',
  '38,548,796',
  '1,144,417',
  '33,684,208 ',
  'South America',
  '',
  '71531',
  '',
  '',
  '115'],
 ['36',
  'Switzerland',
  '4,402,438',
  '',
  '14,452                                ',
  '',
  '4,383,180',
  '',
  '4,806',
  '39',
  '501,780',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '548'],
 ['37',
  'Philippines',
  '4,096,335',
  '',
  '66,444                                ',
  '',
  '4,022,326',
  '',
  '7,565',
  '162',
  '36,409',
  '591',
  '35,037,470',
  '311,419',
  '112,508,994 ',
  'Asia',
  '',
  '271,6933',
  '',
  '',
  '67'],
 ['38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010'],
 ['39',
  'Romania',
  '3,393,902',
  '',
  '68,089                                ',
  '',
  '3,314,667',
  '',
  '11,146',
  '128',
  '178,332',
  '3,578',
  '27,242,332',
  '1,431,446',
  '19,031,335 ',
  'Europe',
  '',
  '62801',
  '',
  '',
  '586'],
 ['40',
  'Denmark',
  '3,180,726',
  '',
  '8,572                                ',
  '',
  '3,171,359',
  '',
  '795',
  '19',
  '545,116',
  '1,469',
  '129,268,444',
  '22,154,165',
  '5,834,950 ',
  'Europe',
  '',
  '26810',
  '',
  '',
  '136'],
 ['41',
  'Hong Kong',
  '2,892,450',
  '',
  '13,563                                ',
  '',
  '2,871,114',
  '',
  '7,773',
  '28',
  '380,370',
  '1,784',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35610',
  '',
  '',
  '1,022'],
 ['42',
  'Sweden',
  '2,707,189',
  '',
  '24,141                                ',
  '',
  '2,678,950',
  '',
  '4,098',
  '8',
  '264,918',
  '2,362',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '44231',
  '',
  '',
  '401'],
 ['43',
  'Serbia',
  '2,536,159',
  '',
  '18,022                                ',
  '',
  '2,509,836',
  '',
  '8,301',
  '15',
  '293,095',
  '2,083',
  '12,806,989',
  '1,480,061',
  '8,653,016 ',
  'Europe',
  '',
  '34801',
  '',
  '',
  '959'],
 ['44',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16'],
 ['45',
  'Singapore',
  '2,340,779',
  '',
  '1,727                                ',
  '',
  '2,149,583',
  '',
  '189,469',
  '2',
  '393,835',
  '291',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '33,4420',
  '',
  '',
  '31,878'],
 ['46',
  'New Zealand',
  '2,324,094',
  '',
  '4,154                                ',
  '',
  '2,310,320',
  '',
  '9,620',
  '',
  '474,479',
  '848',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,1791',
  '',
  '',
  '1,964'],
 ['47',
  'Hungary',
  '2,201,355',
  '',
  '48,846                                ',
  '',
  '2,148,647',
  '',
  '3,862',
  '13',
  '229,158',
  '5,085',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41971',
  '',
  '',
  '402'],
 ['48',
  'Bangladesh',
  '2,038,250',
  '',
  '29,446                                ',
  '',
  '1,998,448',
  '',
  '10,356',
  'N/A',
  '12,141',
  '175',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,70111',
  '',
  '',
  '62'],
 ['49',
  'Slovakia',
  '1,866,470',
  '',
  '21,167                                ',
  '',
  '1,845,061',
  '+33',
  '242',
  '18',
  '341,832',
  '3,877',
  '7,427,231',
  '1,360,251',
  '5,460,193 ',
  'Europe',
  '',
  '32581',
  '',
  '',
  '44'],
 ['50',
  'Georgia',
  '1,840,187',
  '',
  '17,059                                ',
  '',
  '1,776,548',
  '',
  '46,580',
  '',
  '463,671',
  '4,298',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22330',
  '',
  '',
  '11,737'],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181'],
 ['52',
  'Ireland',
  '1,710,625',
  '',
  '8,866                                ',
  '',
  '1,699,569',
  '',
  '2,190',
  '19',
  '340,748',
  '1,766',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35660',
  '',
  '',
  '436'],
 ['53',
  'Pakistan',
  '1,580,801',
  '',
  '30,658                                ',
  '',
  '1,538,689',
  '',
  '11,454',
  '8',
  '6,888',
  '134',
  '30,571,377',
  '133,215',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4858',
  '',
  '',
  '50'],
 ['54',
  'Norway',
  '1,483,454',
  '',
  '5,213                                ',
  '',
  '1,477,213',
  '',
  '1,028',
  '20',
  '269,162',
  '946',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,0571',
  '',
  '',
  '187'],
 ['55',
  'Finland',
  '1,475,378',
  '',
  '9,373                                ',
  '',
  '1,459,986',
  '',
  '6,019',
  '21',
  '265,597',
  '1,687',
  '12,090,288',
  '2,176,485',
  '5,554,960 ',
  'Europe',
  '',
  '45930',
  '',
  '',
  '1,084'],
 ['56',
  'Kazakhstan',
  '1,411,768',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,900',
  '24',
  '73,510',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '776'],
 ['57',
  'Slovenia',
  '1,343,364',
  '',
  '7,100                                ',
  '',
  '1,328,006',
  '',
  '8,258',
  '8',
  '646,459',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '',
  '',
  '3,974'],
 ['58',
  'Lithuania',
  '1,318,786',
  '',
  '9,669                                ',
  '',
  '1,307,212',
  '',
  '1,905',
  '2',
  '495,466',
  '3,633',
  '10,439,469',
  '3,922,094',
  '2,661,708 ',
  'Europe',
  '',
  '22750',
  '',
  '',
  '716'],
 ['59',
  'Bulgaria',
  '1,305,030',
  '',
  '38,339                                ',
  '',
  '1,264,067',
  '',
  '2,624',
  '30',
  '190,666',
  '5,601',
  '11,190,426',
  '1,634,928',
  '6,844,597 ',
  'Europe',
  '',
  '51791',
  '',
  '',
  '383'],
 ['60',
  'Morocco',
  '1,273,463',
  '',
  '16,297                                ',
  '',
  '1,256,151',
  '',
  '1,015',
  '3',
  '33,714',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '27'],
 ['61',
  'Croatia',
  '1,272,886',
  '',
  '18,180                                ',
  '',
  '1,253,558',
  '',
  '1,148',
  '6',
  '313,574',
  '4,479',
  '5,582,393',
  '1,375,215',
  '4,059,286 ',
  'Europe',
  '',
  '32231',
  '',
  '',
  '283'],
 ['62',
  'Guatemala',
  '1,248,823',
  '',
  '20,196                                ',
  '',
  '1,227,381',
  '',
  '1,246',
  '5',
  '67,199',
  '1,087',
  '7,235,362',
  '389,332',
  '18,584,039 ',
  'North America',
  '',
  '159203',
  '',
  '',
  '67'],
 ['63',
  'Lebanon',
  '1,236,971',
  '',
  '10,904                                ',
  '',
  '1,087,587',
  '',
  '138,480',
  '74',
  '185,041',
  '1,631',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56131',
  '',
  '',
  '20,716'],
 ['64',
  'Costa Rica',
  '1,228,659',
  '',
  '9,351                                ',
  '',
  '860,711',
  '',
  '358,597',
  '52',
  '237,085',
  '1,804',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45541',
  '',
  '',
  '69,196'],
 ['65',
  'Bolivia',
  '1,197,458',
  '',
  '22,377                                ',
  '',
  '1,166,413',
  '',
  '8,668',
  '220',
  '99,849',
  '1,866',
  '2,705,422',
  '225,590',
  '11,992,656 ',
  'South America',
  '',
  '105364',
  '',
  '',
  '723'],
 ['66',
  'Tunisia',
  '1,152,877',
  '',
  '29,398                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,701',
  '2,440',
  '5,010,521',
  '415,926',
  '12,046,656 ',
  'Africa',
  '',
  '104102',
  '',
  '',
  '1,119'],
 ['67',
  'Cuba',
  '1,113,374',
  '',
  '8,530                                ',
  '',
  '1,104,696',
  '',
  '148',
  '2',
  '98,479',
  '754',
  '14,345,279',
  '1,268,859',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '',
  '',
  '13'],
 ['68',
  'UAE',
  '1,063,002',
  '',
  '2,349                                ',
  '',
  '1,046,765',
  '',
  '13,888',
  '',
  '105,438',
  '233',
  '200,369,120',
  '19,874,369',
  '10,081,785 ',
  'Asia',
  '',
  '94,2920',
  '',
  '',
  '1,378'],
 ['69',
  'Ecuador',
  '1,061,100',
  '',
  '36,019                                ',
  '',
  '1,023,510',
  '',
  '1,571',
  '759',
  '58,581',
  '1,989',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175036',
  '',
  '',
  '87'],
 ['70',
  'Uruguay',
  '1,037,893',
  '',

In [15]:
import csv
file = open('covid_data.csv', 'w')
x = csv.writer(file)
x.writerows(final_data)

In [16]:
import pandas as pd
df=pd.read_csv('covid_data.csv', encoding='latin1')
df

                                                                                                #  \
NaN   NaN              North America NaN 126,309,685                           NaN      1,630,352
                       Asia          NaN 216,724,187                           +18,459  1,544,873
                       Europe        NaN 248,938,503                           NaN      2,053,808
                       South America NaN 68,600,642                            NaN      1,354,635
                       Oceania       NaN 14,182,986                            NaN         27,278
...                                                                                           ...
137.0 New Caledonia    79,922        NaN 314                                   NaN         79,605
138.0 French Polynesia 78,488        NaN 649                                   NaN            NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN         73,116
140.0 Guyana           73,168        NaN 1,298                                 NaN         71,827
141.0 Belize           70,782        NaN 688                                   NaN         70,085

                                                                                       Country,Other  \
NaN   NaN              North America NaN 126,309,685                           NaN               NaN
                       Asia          NaN 216,724,187                           +18,459            +6
                       Europe        NaN 248,938,503                           NaN               NaN
                       South America NaN 68,600,642                            NaN               NaN
                       Oceania       NaN 14,182,986                            NaN               NaN
...                                                                                              ...
137.0 New Caledonia    79,922        NaN 314                                   NaN               NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN               NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN               NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN               NaN
141.0 Belize           70,782        NaN 688                                   NaN               NaN

                                                                                         TotalCases  \
NaN   NaN              North America NaN 126,309,685                           NaN      122,090,281
                       Asia          NaN 216,724,187                           +18,459  200,607,206
                       Europe        NaN 248,938,503                           NaN      244,762,390
                       South America NaN 68,600,642                            NaN       66,449,498
                       Oceania       NaN 14,182,986                            NaN       14,020,441
...                                                                                             ...
137.0 New Caledonia    79,922        NaN 314                                   NaN                3
138.0 French Polynesia 78,488        NaN 649                                   NaN              NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN               86
140.0 Guyana           73,168        NaN 1,298                                 NaN               43
141.0 Belize           70,782        NaN 688                                   NaN                9

                                                                                       NewCases  \
NaN   NaN              North America NaN 126,309,685                           NaN       +1,003
                       Asia          NaN 216,724,187                           +18,459   +4,932
                       Europe        NaN 248,938,503                           NaN       +2,996
                       South America NaN 68,600,642                            NaN          NaN
                       Oceania       NaN 14,182,986                            NaN          NaN
...                                                                                         ...
137.0 New Caledonia    79,922        NaN 314                                   NaN            9
138.0 French Polynesia 78,488        NaN 649                                   NaN            7
139.0 Eswatini         74,627        NaN 1,425                                 NaN          NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN          NaN
141.0 Belize           70,782        NaN 688                                   NaN            6

                                                                                       TotalDeaths  \
NaN   NaN              North America NaN 126,309,685                           NaN       2,589,052
                       Asia          NaN 216,724,187                           +18,459  14,572,108
                       Europe        NaN 248,938,503                           NaN       2,122,305
                       South America NaN 68,600,642                            NaN         796,509
                       Oceania       NaN 14,182,986                            NaN         135,267
...                                                                                            ...
137.0 New Caledonia    79,922        NaN 314                                   NaN         274,726
138.0 French Polynesia 78,488        NaN 649                                   NaN         276,207
139.0 Eswatini         74,627        NaN 1,425                                 NaN          62,986
140.0 Guyana           73,168        NaN 1,298                                 NaN          92,146
141.0 Belize           70,782        NaN 688                                   NaN         171,722

                                                                                       NewDeaths  \
NaN   NaN              North America NaN 126,309,685                           NaN         6,413
                       Asia          NaN 216,724,187                           +18,459    15,649
                       Europe        NaN 248,938,503                           NaN         6,362
                       South America NaN 68,600,642                            NaN        10,134
                       Oceania       NaN 14,182,986                            NaN            89
...                                                                                          ...
137.0 New Caledonia    79,922        NaN 314                                   NaN         1,079
138.0 French Polynesia 78,488        NaN 649                                   NaN         2,284
139.0 Eswatini         74,627        NaN 1,425                                 NaN         1,203
140.0 Guyana           73,168        NaN 1,298                                 NaN         1,635
141.0 Belize           70,782        NaN 688                                   NaN         1,669

                                                                                       TotalRecovered  \
NaN   NaN              North America NaN 126,309,685                           NaN                NaN
                       Asia          NaN 216,724,187                           +18,459            NaN
                       Europe        NaN 248,938,503                           NaN                NaN
                       South America NaN 68,600,642                            NaN                NaN
                       Oceania       NaN 14,182,986                            NaN                NaN
...                                                                                               ...
137.0 New Caledonia    79,922        NaN 314                                   NaN             98,964
138.0 French Polynesia 78,488        NaN 649                                   NaN                NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN          1,048,704
140.0 Guyana           73,168        NaN 1,298                                 NaN            728,813
141.0 Belize           70,782        NaN 688                                   NaN            576,016

                                                                                       NewRecovered  \
NaN   NaN              North America NaN 126,309,685                           NaN              NaN
                       Asia          NaN 216,724,187                           +18,459          NaN
                       Europe        NaN 248,938,503                           NaN              NaN
                       South America NaN 68,600,642                            NaN              NaN
                       Oceania       NaN 14,182,986                            NaN              NaN
...                                                                                             ...
137.0 New Caledonia    79,922        NaN 314                                   NaN          340,182
138.0 French Polynesia 78,488        NaN 649                                   NaN              NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN          885,119
140.0 Guyana           73,168        NaN 1,298                                 NaN          917,848
141.0 Belize           70,782        NaN 688                                   NaN        1,397,453

                                                                                       ActiveCases  \
NaN   NaN              North America NaN 126,309,685                           NaN             NaN
                       Asia          NaN 216,724,187                           +18,459         NaN
                       Europe        NaN 248,938,503                           NaN             NaN
                       South America NaN 68,600,642                            NaN             NaN
                       Oceania       NaN 14,182,986                            NaN             NaN
...                                                                                            ...
137.0 New Caledonia    79,922        NaN 314                                   NaN        290,915
138.0 French Polynesia 78,488        NaN 649                                   NaN        284,164
139.0 Eswatini         74,627        NaN 1,425                                 NaN      1,184,817
140.0 Guyana           73,168        NaN 1,298                                 NaN        794,045
141.0 Belize           70,782        NaN 688                                   NaN        412,190

                                                                                         Serious,Critical  \
NaN   NaN              North America NaN 126,309,685                           NaN                    NaN
                       Asia          NaN 216,724,187                           +18,459                NaN
                       Europe        NaN 248,938,503                           NaN                    NaN
                       South America NaN 68,600,642                            NaN                    NaN
                       Oceania       NaN 14,182,986                            NaN                    NaN
...                                                                                                   ...
137.0 New Caledonia    79,922        NaN 314                                   NaN      Australia/Oceania
138.0 French Polynesia 78,488        NaN 649                                   NaN      Australia/Oceania
139.0 Eswatini         74,627        NaN 1,425                                 NaN                 Africa
140.0 Guyana           73,168        NaN 1,298                                 NaN          South America
141.0 Belize           70,782        NaN 688                                   NaN          North America

                                                                                        ...  \
NaN   NaN              North America NaN 126,309,685                           NaN      ...
                       Asia          NaN 216,724,187                           +18,459  ...
                       Europe        NaN 248,938,503                           NaN      ...
                       South America NaN 68,600,642                            NaN      ...
                       Oceania       NaN 14,182,986                            NaN      ...
...                                                                                     ...
137.0 New Caledonia    79,922        NaN 314                                   NaN      ...
138.0 French Polynesia 78,488        NaN 649                                   NaN      ...
139.0 Eswatini         74,627        NaN 1,425                                 NaN      ...
140.0 Guyana           73,168        NaN 1,298                                 NaN      ...
141.0 Belize           70,782        NaN 688                                   NaN      ...

                                                                                        TotalTests  \
NaN   NaN              North America NaN 126,309,685                           NaN             NaN
                       Asia          NaN 216,724,187                           +18,459         NaN
                       Europe        NaN 248,938,503                           NaN             NaN
                       South America NaN 68,600,642                            NaN             NaN
                       Oceania       NaN 14,182,986                            NaN             NaN
...                                                                                            ...
137.0 New Caledonia    79,922        NaN 314                                   NaN             NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN             NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN             NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN             NaN
141.0 Belize           70,782        NaN 688                                   NaN             NaN

                                                                                       Tests/  \
NaN   NaN              North America NaN 126,309,685                           NaN        NaN
                       Asia          NaN 216,724,187                           +18,459    NaN
                       Europe        NaN 248,938,503                           NaN        NaN
                       South America NaN 68,600,642                            NaN        NaN
                       Oceania       NaN 14,182,986                            NaN        NaN
...                                                                                       ...
137.0 New Caledonia    79,922        NaN 314                                   NaN        NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN        NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN        NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN        NaN
141.0 Belize           70,782        NaN 688                                   NaN        NaN

                                                                                         1M pop  \
NaN   NaN              North America NaN 126,309,685                           NaN          NaN
                       Asia          NaN 216,724,187                           +18,459      NaN
                       Europe        NaN 248,938,503                           NaN          NaN
                       South America NaN 68,600,642                            NaN          NaN
                       Oceania       NaN 14,182,986                            NaN          NaN
...                                                                                         ...
137.0 New Caledonia    79,922        NaN 314                                   NaN           10
138.0 French Polynesia 78,488        NaN 649                                   NaN      156,033
139.0 Eswatini         74,627        NaN 1,425                                 NaN           73
140.0 Guyana           73,168        NaN 1,298                                 NaN           54
141.0 Belize           70,782        NaN 688                                   NaN           22

                                                                                        Unnamed: 15  \
NaN   NaN              North America NaN 126,309,685                           NaN              NaN
                       Asia          NaN 216,724,187                           +18,459          NaN
                       Europe        NaN 248,938,503                           NaN              NaN
                       South America NaN 68,600,642                            NaN              NaN
                       Oceania       NaN 14,182,986                            NaN              NaN
...                                                                                             ...
137.0 New Caledonia    79,922        NaN 314                                   NaN              NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN              NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN              NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN              NaN
141.0 Belize           70,782        NaN 688                                   NaN              NaN

                                                                                       Population  \
NaN   NaN              North America NaN 126,309,685                           NaN            NaN
                       Asia          NaN 216,724,187                           +18,459        NaN
                       Europe        NaN 248,938,503                           NaN            NaN
                       South America NaN 68,600,642                            NaN            NaN
                       Oceania       NaN 14,182,986                            NaN            NaN
...                                                                                           ...
137.0 New Caledonia    79,922        NaN 314                                   NaN            NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN            NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN            NaN
140.0 Guyana           73,168        NaN 1,298                                 NaN            NaN
141.0 Belize           70,782        NaN 688                                   NaN            NaN

                                                                                        Continent  \
NaN   NaN              North America NaN 126,309,685                           NaN            NaN
                       Asia          NaN 216,724,187                           +18,459        NaN
                       Europe        NaN 248,938,503                           NaN            NaN
                       South America NaN 68,600,642                            NaN            NaN
                       Oceania       NaN 14,182,986                            NaN            NaN
...                                                                                           ...
137.0 New Caledonia    79,922        NaN 314                                   NaN            NaN
138.0 French Polynesia 78,488        NaN 649                                   NaN            NaN
139.0 Eswatini         74,627        NaN 1,425                                 NaN            NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 149 entries, (nan, nan, 'North America', nan, '126,309,685', nan) to (141.0, 'Belize', '70,782', nan, '688                                ', nan)
Data columns (total 22 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   #                                                     138 non-null    object
 1   Country,Other                                         8 non-null      object
 2   TotalCases                                            138 non-null    object
 3   NewCases                                              101 non-null    object
 4   TotalDeaths                                           149 non-null    object
 5   NewDeaths                                             149 non-null    object
 6   TotalRecovered                                        139 non-null    object
 7   NewRecovered                                          139 non-null    object
 8   ActiveCases                                           141 non-null    object
 9   Serious,Critical                                      142 non-null    object
 10  Tot Cases/1M pop                                      0 non-null      float64
 11  Deaths/1M pop                                         147 non-null    object
 12  TotalTests                                            1 non-null      float64
 13  Tests/                                                1 non-null      float64
 14  1M pop                                                137 non-null    object
 15  Unnamed: 15                                           0 non-null      float64
 16  Population                                            0 non-null      float64
 17  Continent                                             0 non-null      float64
 18  1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl  0 non-null      float64
 19  New Cases/1M pop                                      0 non-null      float64
 20  New Deaths/1M pop                                     0 non-null      float64
 21  Active Cases/1M pop                                   0 non-null      float64
dtypes: float64(10), object(12)
memory usage: 48.2+ KB

In [18]:
df['TotalCases']

NaN    NaN               North America  NaN  126,309,685                            NaN        122,090,281
                         Asia           NaN  216,724,187                            +18,459    200,607,206
                         Europe         NaN  248,938,503                            NaN        244,762,390
                         South America  NaN  68,600,642                             NaN         66,449,498
                         Oceania        NaN  14,182,986                             NaN         14,020,441
                                                                                                  ...
137.0  New Caledonia     79,922         NaN  314                                    NaN                  3
138.0  French Polynesia  78,488         NaN  649                                    NaN                NaN
139.0  Eswatini          74,627         NaN  1,425                                  NaN                 86
140.0  Guyana            73,168         NaN  1,298                                  NaN                 43
141.0  Belize            70,782         NaN  688                                    NaN                  9
Name: TotalCases, Length: 149, dtype: object

In [24]:
df =

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1567902797.py, line 1)

In [ ]:
list(map(lambda x:int(x.replace(',',' ')), list(df['TotalCases'][])))

In [1]:
pwd

'C:\\Users\\User\\ADB'